#!/bin/sh

set -e

case "$1" in
remove)
  #echo "Removing package... (after)"
  W=$(cat /etc/passwd | grep wolken | wc -l) 
  if [ $W -eq 1 ]; then 
    echo "Removing wolken user..."
    userdel wolken
  else
    echo "Warning: wolken user didn't exist."
  fi
  ;;
upgrade)
  #echo "Removing previous version... (after)"
  ;;
esac

#DEBHELPER#

exit 0
