#!/bin/sh

set -e

XDG="/etc/xdg/wolken/wolken.conf"
GAL_PATH="/usr/share/wolken/gal" # Gallery path
IMG_PATH="/usr/share/wolken/img" # Captures path
IMG_LINK=$GAL_PATH"/wolken"    # Soft link to captures

case "$1" in
configure)
  #echo "Instaling/updating package... (after)"
    if [ -f $XDG ]; then
      echo "Changing privileges to XDG file..."
      chown -R wolken:wolken $(dirname $XDG)
      chmod 700 $(dirname $XDG)
      chmod 600 $XDG
    else
      echo "Warning: XDG doesn't exists."
    fi
    
    if [ -d $GAL_PATH -a -d $IMG_PATH -a ! -e $IMG_LINK ]; then
      ln -fs $IMG_LINK $GAL_PATH
    else
      echo "Warning: Couldn't create link to captures."
    fi
  ;;
esac

#DEBHELPER#

exit 0
