#!/bin/sh

set -e

XDG="/etc/xdg/wolken/wolken.conf"
GAL_PATH="/var/www/wolken/gal" # Ruta de la galería
IMG_PATH="/var/www/wolken/img" # Ruta de las capturas
IMG_LINK=$GAL_PATH"/wolken"    # Enlace a las capturas

case "$1" in
configure)
    #echo "Instalando/actualizando paquete... (después)"
    if [ -f $XDG ]; then
      echo "Cambiando permisos al archivo XDG..."
      chown -R wolken:wolken $(dirname $XDG)
      chmod 700 $(dirname $XDG)
      chmod 600 $XDG
    else
      echo "Aviso: El archivo XDG no existe."
    fi
    
    if [ -d $GAL_PATH -a -d $IMG_PATH -a ! -e $IMG_LINK ]; then
      ln -fs $IMG_LINK $GAL_PATH
    else
      echo "Aviso: No se pudo crear el enlace a las capturas."
    fi
  ;;
esac

exit 0
