#!/bin/sh

set -e

case "$1" in
install)
    #echo "Installing package... (before)"
    W=$(cat /etc/passwd | grep wolken | wc -l) 
    if [ $W -eq 0 ]; then 
      echo "Creating wolken user..."
      useradd wolken -d /var/www/wolken
      usermod -G video,plugdev wolken
    else
      echo "Warning: wolken user already exists."
    fi
  ;;
upgrade)
  #echo "Updating package... (before)"
  ;;
esac

exit 0

