#!/bin/sh

set -e

GAL_PATH="/usr/share/wolken/gal" # Gallery path
IMG_PATH="/usr/share/wolken/img" # Captures path
IMG_LINK=$GAL_PATH"/wolken"    # Soft link to captures

case "$1" in
remove)
  #echo "Removing package... (before)"
  if [ -e $IMG_LINK ]; then
    echo "Removing link to captures..."
    rm -f $IMG_LINK
  fi
  ;;
upgrade)
  #echo "Removing previous version... (before)"
  ;;
esac

#DEBHELPER#

exit 0
